version: '3'
services:
  python3:
    build: .
    container_name: nakadaka_flask_app
    hostname: nakadaka_flask_app
    tty: true
    volumes:
      - ./app:/app
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
